<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>77e15ea2-1beb-4c61-b309-8bf37c20c773</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MISA.Common\MISA.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Dapper" Version="2.1.72" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="11.0.0-preview.3.26207.106" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="11.0.0-preview.3.26207.106" />
      <PackageReference Include="MySqlConnector" Version="2.5.0" />
    </ItemGroup>

</Project>
